import { useMemo } from "react";

export interface CategoriesData {
  Categorias: string[];
  countries: string[];
  departments: {
    [key: string]: string[];
  };
  cities: {
    [key: string]: string[];
  };
  localities: {
    [key: string]: string[];
  };
}

export function useCategoriesData(): CategoriesData {
  return useMemo(
    () => ({
      Categorias: ["S", "M", "W", "T", "L", "G", "P"],
      countries: ["COLOMBIA", "PERU"],
      departments: {
        COLOMBIA: [
          "AMAZONAS",
          "ANTIOQUIA",
          "ARAUCA",
          "ATLANTICO",
          "BOGOTA",
          "BOLIVAR",
          "BOYACA",
          "CALDAS",
          "CAQUETA",
          "CASANARE",
          "CAUCA",
          "CESAR",
          "CHOCO",
          "CORDOBA",
          "CUNDINAMARCA",
          "GUANIA",
          "GUAVIARE",
          "HUILA",
          "GUAJIRA",
          "MAGDALENA",
          "META",
          "NARIÑO",
          "NORTE_DE_SANTANDER",
          "PUTUMAYO",
          "QUINDIO",
          "RISARALDA",
          "SAN_ANDRES",
          "SANTANDER",
          "SUCRE",
          "TOLIMA",
          "VALLE",
          "VAUPES",
          "VICHADA",
        ],
        PERU: ["LIMA"],
      },
      cities: {
        AMAZONAS: ["LETICIA", "PUERTO_SANTANDER", "PUERTO_NARIÑO"],
        ANTIOQUIA: [
          "MEDELLIN",
          "Abejorral",
          "Abriaquí",
          "Alejandría",
          "Amagá",
          "Amalfi",
          "Andes",
          "Angelópolis",
          "Angostura",
          "Anorí",
          "Anzá",
          "Apartadó",
          "Arboletes",
          "Argelia",
          "Armenia",
          "Barbosa",
          "Bello",
          "Belmira",
          "Betania",
          "Betulia",
          "Briceño",
          "Buriticá",
          "Cáceres",
          "Caicedo",
          "Caldas",
          "Campamento",
          "Cañasgordas",
          "Caracolí",
          "Caramanta",
          "Carepa",
          "Carolina del Príncipe",
          "Caucasia",
          "Chigorodó",
          "Cisneros",
          "Cocorná",
          "Concepción",
          "Concordia",
          "Copacabana",
          "Dabeiba",
          "Donmatías",
          "Ebéjico",
          "El Bagre",
          "El Carmen de Viboral",
          "El Peñol",
          "El Retiro",
          "El Santuario",
          "Entrerríos",
          "Envigado",
          "Fredonia",
          "Frontino",
          "Giraldo",
          "Girardota",
          "Gómez Plata",
          "Granada",
          "Guadalupe",
          "Guarne",
          "Guatapé",
          "Heliconia",
          "Hispania",
          "Itagüí",
          "Ituango",
          "Jardín",
          "Jericó",
          "La Ceja",
          "La Estrella",
          "La Pintada",
          "La Unión",
          "Liborina",
          "Maceo",
          "Marinilla",
          "Medellín",
          "Montebello",
          "Murindó",
          "Mutatá",
          "Nariño",
          "Nechí",
          "Necoclí",
          "Olaya",
          "Peque",
          "Pueblorrico",
          "Puerto Berrío",
          "Puerto Nare",
          "Puerto Triunfo",
          "Remedios",
          "Rionegro",
          "Sabanalarga",
          "Sabaneta",
          "Salgar",
          "San Andrés de Cuerquia",
          "San Carlos",
          "San Francisco",
          "San Jerónimo",
          "San José de la Montaña",
          "San Juan de Urabá",
          "San Luis",
          "San Pedro de los Milagros",
          "San Pedro de Urabá",
          "San Rafael",
          "San Roque",
          "San Vicente Ferrer",
          "Santa Bárbara",
          "Santa Fe de Antioquia",
          "Santa Rosa de Osos",
          "Santo Domingo",
          "Segovia",
          "Sonsón",
          "Sopetrán",
          "Támesis",
          "Tarazá",
          "Tarso",
          "Titiribí",
          "Toledo",
          "Turbo",
          "Uramita",
          "Urrao",
          "Valdivia",
          "Valparaíso",
          "Vegachí",
          "Venecia",
          "Vigía del Fuerte",
          "Yalí",
          "Yarumal",
          "Yolombó",
          "Yondó",
          "Zaragoza",
        ],
        ARAUCA: [
          "ARAUCA",
          "Arauquita",
          "Cravo Norte",
          "Fortul",
          "Puerto Rondón",
          "Saravena",
          "Tame",
        ],
        ATLANTICO: [
          "Baranoa",
          "BARRANQUILLA",
          "Campo de la Cruz",
          "Candelaria",
          "Galapa",
          "Juan de Acosta",
          "Luruaco",
          "Malambo",
          "Manatí",
          "Palmar de Varela",
          "Polonuevo",
          "Ponedera",
          "Puerto Colombia",
          "Repelón",
          "Sabanagrande",
          "Sabanalarga",
          "Santo Tomás",
          "Soledad",
          "Suan",
          "Tubará",
          "Usiacurí",
        ],
        BOGOTA: ["BOGOTA"],
        BOLIVAR: [
          "Achí",
          "Altos del Rosario",
          "Arenal",
          "Arjona",
          "Arroyohondo",
          "Barranco de Loba",
          "Calamar",
          "Cantagallo",
          "CARTAGENA_DE_INDIAS",
          "Cicuco",
          "Clemencia",
          "Córdoba",
          "El Carmen de Bolívar",
          "El Guamo",
          "El Peñón",
          "Hatillo de Loba",
          "Magangué",
          "Mahates",
          "Margarita",
          "María La Baja",
          "Montecristo",
          "Morales",
          "Norosí",
          "Pinillos",
          "Regidor",
          "Río Viejo",
          "San Cristóbal",
          "San Estanislao",
          "San Fernando",
          "San Jacinto",
          "San Jacinto del Cauca",
          "San Juan Nepomuceno",
          "San Martín de Loba",
          "San Pablo",
          "Santa Catalina",
          "Santa Cruz de Mompox",
          "Santa Rosa",
          "Santa Rosa del Sur",
          "Simití",
          "Soplaviento",
          "Talaigua Nuevo",
          "Tiquisio",
          "Turbaco",
          "Turbaná",
          "Villanueva",
          "Zambrano",
        ],
        BOYACA: [
          "Almeida",
          "Aquitania",
          "Arcabuco",
          "Belén",
          "Berbeo",
          "Betéitiva",
          "Boavita",
          "Boyacá",
          "Briceño",
          "Buenavista",
          "Busbanzá",
          "Caldas",
          "Campohermoso",
          "Cerinza",
          "Chinavita",
          "Chiquinquirá",
          "Chíquiza",
          "Chiscas",
          "Chita",
          "Chitaraque",
          "Chivatá",
          "Chivor",
          "Ciénaga",
          "Cómbita",
          "Copacabana",
          "Coper",
          "Corrales",
          "Covarachía",
          "Cubará",
          "Cucaita",
          "Cuítiva",
          "Duitama",
          "El Cocuy",
          "El Espino",
          "Firavitoba",
          "Floresta",
          "Gachantivá",
          "Gameza",
          "Garagoa",
          "Guacamayas",
          "Guateque",
          "Guayatá",
          "Guicán",
          "Iza",
          "Jenesano",
          "Jericó",
          "La Capilla",
          "La Uvita",
          "La Victoria",
          "Labranzagrande",
          "Macanal",
          "Maripí",
          "Miraflores",
          "Mongua",
          "Monguí",
          "Moniquirá",
          "Motavita",
          "Muzo",
          "Nobsa",
          "Nuevo Colón",
          "Oicatá",
          "Otanche",
          "Pachavita",
          "Páez",
          "Paipa",
          "Pajarito",
          "Panqueba",
          "Pauna",
          "Paya",
          "Paz de Río",
          "Pesca",
          "Pisba",
          "Puerto Boyacá",
          "Quípama",
          "Ramiriquí",
          "Ráquira",
          "Rondón",
          "Saboyá",
          "Sáchica",
          "Samacá",
          "San Eduardo",
          "San José de Pare",
          "San Luis de Gaceno",
          "San Mateo",
          "San Miguel de Sema",
          "San Pablo de Borbur",
          "Santa María",
          "Santa Rosa de Viterbo",
          "Santa Sofía",
          "Santana",
          "Sativanorte",
          "Sativasur",
          "Siachoque",
          "Soatá",
          "Socha",
          "Sogamoso",
          "Somondoco",
          "Sora",
          "Soracá",
          "Sotaquirá",
          "Susacón",
          "Sutamarchán",
          "Sutatenza",
          "Tasco",
          "Tenza",
          "Tibaná",
          "Tibasosa",
          "Tinjacá",
          "Tipacoque",
          "Toca",
          "Togüí",
          "Tópaga",
          "Tota",
          "TUNJA",
          "Tununguá",
          "Turmequé",
          "Tuta",
          "Tutazá",
          "Úmbita",
          "Ventaquemada",
          "Villa de Leyva",
          "Viracachá",
          "Zetaquira",
        ],
        CALDAS: [
          "Aguadas",
          "Anserma",
          "Aranzazu",
          "Belalcázar",
          "Chinchiná",
          "Filadelfia",
          "La Dorada",
          "La Merced",
          "MANIZALES",
          "Manzanares",
          "Marmato",
          "Marquetalia",
          "Marulanda",
          "Neira",
          "Norcasia",
          "Pácora",
          "Palestina",
          "Pensilvania",
          "Riosucio",
          "Risaralda",
          "Salamina",
          "Samaná",
          "San José",
          "Supía",
          "Victoria",
          "Villamaría",
          "Viterbo",
        ],
        CAQUETA: [
          "Albania",
          "Belén de los Andaquíes",
          "Cartagena del Chairá",
          "Curillo",
          "El Doncello",
          "El Paujil",
          "FLORENCIA",
          "La Montañita",
          "Milán",
          "Morelia",
          "Puerto Rico",
          "San José del Fragua",
          "San Vicente del Caguán",
          "Solano",
          "Solita",
          "Valparaíso",
        ],
        CASANARE: [
          "YOPAL",
          "Aguazul",
          "Chámeza",
          "Hato Corozal",
          "La Salina",
          "Maní",
          "Monterrey",
          "Nunchía",
          "Orocué",
          "Paz de Ariporo",
          "Pore",
          "Recetor",
          "Sabanalarga",
          "Sácama",
          "San Luis de Palenque",
          "Támara",
          "Tauramena",
          "Trinidad",
          "Villanueva",
        ],
        CAUCA: [
          "POPAYAN",
          "Almaguer",
          "Argelia",
          "Balboa",
          "Bolívar",
          "Buenos Aires",
          "Cajibío",
          "Caldono",
          "Caloto",
          "Corinto",
          "El Tambo",
          "Florencia",
          "Guachené",
          "Guapi",
          "Inzá",
          "Jambaló",
          "La Sierra",
          "La Vega",
          "López de Micay",
          "Mercaderes",
          "Miranda",
          "Morales",
          "Padilla",
          "Páez",
          "Patía",
          "Piamonte",
          "Piendamó",

          "Puerto Tejada",
          "Puracé",
          "Rosas",
          "San Sebastián",
          "Santander de Quilichao",
          "Santa Rosa",
          "Silvia",
          "Sotará",
          "Suárez",
          "Sucre",
          "Timbío",
          "Timbiquí",
          "Toribío",
          "Totoró",
          "Villa Rica",
        ],
        CESAR: [
          "VALLEDUPAR",
          "Aguachica",
          "Agustín Codazzi",
          "Astrea",
          "Becerril",
          "Bosconia",
          "Chimichagua",
          "Chiriguaná",
          "Curumaní",
          "El Copey",
          "El Paso",
          "Gamarra",
          "González",
          "La Gloria",
          "La Jagua de Ibirico",
          "La Paz",
          "Manaure Balcón del Cesar",
          "Pailitas",
          "Pelaya",
          "Pueblo Bello",
          "Río de Oro",
          "San Alberto",
          "San Diego",
          "San Martín",
          "Tamalameque",
        ],
        CHOCO: [
          "QUIBDO",
          "Acandí",
          "Alto Baudó",
          "Atrato",
          "Bagadó",
          "Bahía Solano",
          "Bajo Baudó",
          "Bojayá",
          "Carmen del Darién",
          "Cértegui",
          "Condoto",
          "El Cantón del San Pablo",
          "El Carmen de Atrato",
          "El Litoral del San Juan",
          "Istmina",
          "Jurado",
          "Lloró",
          "Medio Atrato",
          "Medio Baudó",
          "Medio San Juan",
          "Nóvita",
          "Nuquí",

          "Río Iró",
          "Río Quito",
          "Riosucio",
          "San José del Palmar",
          "Sipí",
          "Tadó",
          "Unguía",
          "Unión Panamericana",
        ],
        CORDOBA: [
          "MONTERIA",
          "Ayapel",
          "Buenavista",
          "Canalete",
          "Cereté",
          "Chimá",
          "Chinú",
          "Ciénaga de Oro",
          "Cotorra",
          "La Apartada",
          "Lorica",
          "Los Córdobas",
          "Momil",
          "Montelíbano",

          "Moñitos",
          "Planeta Rica",
          "Pueblo Nuevo",
          "Puerto Escondido",
          "Puerto Libertador",
          "Purísima",
          "Sahagún",
          "San Andrés de Sotavento",
          "San Antero",
          "San Bernardo del Viento",
          "San Carlos",
          "San José de Uré",
          "San Pelayo",
          "Tierralta",
          "Valencia",
        ],
        CUNDINAMARCA: [
          "SOACHA",
          "Agua de Dios",
          "Albán",
          "Anapoima",
          "Anolaima",
          "Apulo",
          "Arbeláez",
          "Beltrán",
          "Bituima",
          "Bojacá",
          "Cabrera",
          "Cachipay",
          "Cajicá",
          "Caparrapí",
          "Caqueza",
          "Carmen de Carupa",
          "Chaguaní",
          "Chía",
          "Chipaque",
          "Choachí",
          "Chocontá",
          "Cogua",
          "Cota",
          "Cucunubá",
          "El Colegio",
          "El Peñón",
          "El Rosal",
          "Facatativá",
          "Fomeque",
          "Fosca",
          "Funza",
          "Fúquene",
          "Gachala",
          "Gachancipá",
          "Gachetá",
          "Gama",
          "Girardot",
          "Granada",
          "Guachetá",
          "Guaduas",
          "Guasca",
          "Guataquí",
          "Guatavita",
          "Guayabal de Síquima",
          "Guayabetal",
          "Gutiérrez",
          "Jerusalén",
          "Junín",
          "La Calera",
          "La Mesa",
          "La Palma",
          "La Peña",
          "La Vega",
          "Lenguazaque",
          "Macheta",
          "Madrid",
          "Manta",
          "Medina",
          "Mosquera",
          "Nariño",
          "Nemocón",
          "Nilo",
          "Nimaima",
          "Nocaima",
          "Venecia (Ospina Pérez)",
          "Pacho",
          "Paime",
          "Pandi",
          "Paratebueno",
          "Pasca",
          "Puerto Salgar",
          "Pulí",
          "Quebradanegra",
          "Quetame",
          "Quipile",
          "Ricaurte",
          "San Antonio del Tequendama",
          "San Bernardo",
          "San Cayetano",
          "San Francisco",
          "San Juan de Río Seco",
          "Sasaima",
          "Sesquilé",
          "Sibaté",
          "Silvania",
          "Simijaca",

          "Sopó",
          "Subachoque",
          "Suesca",
          "Supatá",
          "Susa",
          "Sutatausa",
          "Tabio",
          "Tausa",
          "Tena",
          "Tenjo",
          "Tibacuy",
          "Tibirita",
          "Tocaima",
          "Tocancipá",
          "Topaipí",
          "Ubalá",
          "Ubaque",
          "Ubaté",
          "Une",
          "Útica",
          "Vergara",
          "Vianí",
          "Villagómez",
          "Villapinzón",
          "Villeta",
          "Viotá",
          "Yacopí",
          "Zipacón",
          "Zipaquirá",
        ],
        GUANIA: [
          "INIRIDA",
          "Barranco Minas",
          "Cacahual",
          "Pana Pana",
          "Riosucio",
          "San Luis",
        ],
        GUAVIARE: [
          "SAN_JOSE_DEL_GUAVIARE",
          "Calamar",
          "El Retorno",
          "Miraflores",
        ],
        HUILA: [
          "NEIVA",
          "Acevedo",
          "Agrado",
          "Aipe",
          "Algeciras",
          "Baraya",
          "Campoalegre",
          "Colombia",
          "Elías",
          "Garzón",
          "Guadalupe",
          "Hobo",
          "Iquira",
          "Isnos",
          "La Argentina",
          "La Plata",
          "Nátaga",

          "Oporapa",
          "Palermo",
          "Palestina",
          "Pital",
          "Pitalito",
          "Rivera",
          "Saladoblanco",
          "San Agustín",
          "Santa María",
          "Suaza",
          "Tarqui",
          "Tello",
          "Teruel",
          "Tesalia",
          "Timaná",
          "Villavieja",
          "Yaguará",
        ],
        GUAJIRA: [
          "RIOHACHA",
          "Albania",
          "Barrancas",
          "Dibulla",
          "Distracción",
          "El Molino",
          "Fonseca",
          "Hatonuevo",
          "La Jagua del Pilar",
          "Maicao",
          "Manaure",

          "San Juan del Cesar",
          "Uribia",
          "Urumita",
          "Villanueva",
        ],
        MAGDALENA: [
          "SANTA_MARTA",
          "Algarrobo",
          "Aracataca",
          "Ariguaní",
          "Cerro de San Antonio",
          "Chibolo",
          "Concordia",
          "El Banco",
          "El Piñón",
          "El Retén",
          "Fundación",
          "Guamal",
          "Nueva Granada",
          "Pedraza",
          "Pijiño del Carmen",
          "Pivijay",
          "Plato",
          "Puebloviejo",
          "Remolino",
          "Sabanas de San Ángel",
          "Salamina",
          "San Sebastián de Buenavista",
          "San Zenón",
          "Santa Ana",
          "Santa Bárbara de Pinto",

          "Sitionuevo",
          "Tenerife",
          "Zapayán",
          "Zona Bananera",
        ],
        META: [
          "VILLAVICENCIO",
          "Acacías",
          "Barranca de Upía",
          "Cabuyaro",
          "Castilla la Nueva",
          "Cubarral",
          "Cumaral",
          "El Calvario",
          "El Castillo",
          "El Dorado",
          "Fuente de Oro",
          "Granada",
          "Guamal",
          "Mapiripán",
          "Mesetas",
          "La Macarena",
          "Lejanías",
          "Puerto Concordia",
          "Puerto Gaitán",
          "Puerto Lleras",
          "Puerto López",
          "Puerto Rico",
          "Restrepo",
          "San Carlos de Guaroa",
          "San Juan de Arama",
          "San Juanito",
          "San Martín",
          "Uribe",

          "Vista Hermosa",
        ],
        NARIÑO: [
          "PASTO",
          "Aldana",
          "Ancuyá",
          "Barbacoas",
          "Belén",
          "Buesaco",
          "Chachagüí",
          "Colón",
          "Consacá",
          "Contadero",
          "Córdoba",
          "Cuaspud",
          "Cumbal",
          "Cumbitara",
          "El Charco",
          "El Peñol",
          "El Rosario",
          "El Tablón de Gómez",
          "El Tambo",
          "Francisco Pizarro",
          "Funes",
          "Guachucal",
          "Guaitarilla",
          "Gualmatán",
          "Iles",
          "Imués",
          "Ipiales",
          "La Cruz",
          "La Florida",
          "La Llanada",
          "La Tola",
          "La Unión",
          "Leiva",
          "Linares",
          "Los Andes",
          "Magüí",
          "Mallama",
          "Mosquera",
          "Nariño",
          "Olaya Herrera",
          "Ospina",

          "Policarpa",
          "Potosí",
          "Providencia",
          "Puerres",
          "Pupiales",
          "Ricaurte",
          "Roberto Payán",
          "Samaniego",
          "San Andrés de Tumaco",
          "San Bernardo",
          "San Lorenzo",
          "San Pablo",
          "San Pedro de Cartago",
          "Santa Bárbara",
          "Sandoná",
          "Sapuyes",
          "Taminango",
          "Tangua",
          "Torres",
          "Tumaco",
          "Túquerres",
          "Yacuanquer",
        ],
        NORTE_DE_SANTANDER: [
          "CUCUTA",
          "Ábrego",
          "Arboledas",
          "Bochalema",
          "Bucarasica",
          "Cáchira",
          "Cácota",
          "Chinácota",
          "Chitagá",
          "Convención",

          "Cucutilla",
          "Duranía",
          "El Carmen",
          "El Tarra",
          "El Zulia",
          "Gramalote",
          "Hacarí",
          "Herrán",
          "Labateca",
          "La Esperanza",
          "La Playa de Belén",
          "Los Patios",
          "Lourdes",
          "Mutiscua",
          "Ocaña",
          "Pamplona",
          "Pamplonita",
          "Puerto Santander",
          "Ragonvalia",
          "Salazar de Las Palmas",
          "San Calixto",
          "San Cayetano",
          "Santiago",
          "Sardinata",
          "Silos",
          "Teorama",
          "Tibú",
          "Toledo",
          "Villa Caro",
          "Villa del Rosario",
        ],
        PUTUMAYO: [
          "MOCOA",
          "Colón",

          "Orito",
          "Puerto Asís",
          "Puerto Caicedo",
          "Puerto Guzmán",
          "Leguízamo",
          "Sibundoy",
          "San Francisco",
          "San Miguel",
          "Santiago",
          "Valle del Guamuez",
          "Villagarzón",
        ],
        QUINDIO: [
          "ARMENIA",
          "Buenavista",
          "Calarcá",
          "Córdoba",
          "Circasia",
          "Filandia",
          "Génova",
          "La Tebaida",
          "Montenegro",
          "Pijao",
          "Quimbaya",
          "Salento",
        ],
        RISARALDA: [
          "PEREIRA",
          "Apía",
          "Balboa",
          "Belén de Umbría",
          "Dosquebradas",
          "Guática",
          "La Celia",
          "La Virginia",
          "Marsella",
          "Mistrató",

          "Pueblo Rico",
          "Quinchía",
          "Santa Rosa de Cabal",
          "Santuario",
        ],
        SAN_ANDRES: ["San Andrés", "Providencia y Santa Catalina"],
        SANTANDER: [
          "BUCARAMANGA",
          "Aguada",
          "Albania",
          "Aratoca",
          "Barbosa",
          "Barichara",
          "Barrancabermeja",
          "Betulia",
          "Bolívar",
          "Buena Vista",
          "Capitanejo",
          "Carcasí",
          "Cepitá",
          "Cerrito",
          "Charalá",
          "Charta",
          "Chima",
          "Chipatá",
          "Cimitarra",
          "Concepción",
          "Confines",
          "Contratación",
          "Coromoro",
          "Curití",
          "El Carmen de Chucurí",
          "El Guacamayo",
          "El Peñón",
          "El Playón",
          "Encino",
          "Enciso",
          "Florián",
          "Floridablanca",
          "Galán",
          "Gambita",
          "Girón",
          "Guaca",
          "Guadalupe",
          "Guapotá",
          "Guavatá",
          "Güepsa",
          "Hato",
          "Jesús María",
          "Jordán",
          "La Belleza",
          "La Paz",
          "Landázuri",
          "Lebrija",
          "Los Santos",
          "Macaravita",
          "Málaga",
          "Matanza",
          "Mogotes",
          "Molagavita",
          "Ocamonte",
          "Oiba",
          "Onzaga",
          "Palmar",
          "Palmas del Socorro",
          "Páramo",
          "Piedecuesta",
          "Pinchote",
          "Puente Nacional",
          "Puerto Parra",
          "Puerto Wilches",
          "Rionegro",
          "Sabana de Torres",
          "San Andrés",
          "San Benito",
          "San Gil",
          "San Joaquín",
          "San José de Miranda",
          "San Miguel",
          "San Vicente de Chucurí",
          "Santa Bárbara",
          "Santa Helena del Opón",
          "Simacota",
          "Socorro",
          "Suaita",
          "Sucre",
          "Suratá",
          "Tona",
          "Valle de San José",
          "Vélez",
          "Vetas",
          "Villanueva",
          "Zapatoca",
        ],
        SUCRE: [
          "SINCELEJO",
          "Aguachica",
          "Buenavista",
          "Caimito",
          "Chalán",
          "Coloso",
          "Corozal",
          "Coveñas",
          "El Roble",
          "Galeras",
          "Guaranda",
          "La Unión",
          "Los Palmitos",
          "Majagual",
          "Morroa",
          "Ovejas",
          "Palmito",
          "Sampués",
          "San Benito Abad",
          "San Juan de Betulia",
          "San Marcos",
          "San Onofre",
          "San Pedro",
          "Santiago de Tolú",
          "Since",

          "Sucre",
          "Tolú Viejo",
        ],
        TOLIMA: [
          "IBAGUE",
          "Alpujarra",
          "Alvarado",
          "Ambalema",
          "Anzoátegui",
          "Armero",
          "Ataco",
          "Cajamarca",
          "Carmen de Apicalá",
          "Casabianca",
          "Chaparral",
          "Coello",
          "Coyaima",
          "Cunday",
          "Dolores",
          "Espinal",
          "Falan",
          "Flandes",
          "Fresno",
          "Guamo",
          "Herveo",
          "Honda",

          "Icononzo",
          "Lérida",
          "Líbano",
          "Melgar",
          "Murillo",
          "Nariño",
          "Natagaima",
          "Ortega",
          "Palocabildo",
          "Piedras",
          "Planadas",
          "Prado",
          "Purificación",
          "Rioblanco",
          "Roncesvalles",
          "Rovira",
          "Saldaña",
          "San Antonio",
          "San Luis",
          "Santa Isabel",
          "Suárez",
          "Valle de San Juan",
          "Venadillo",
          "Villahermosa",
          "Villarrica",
        ],
        VALLE: [
          "CALI",
          "Alcalá",
          "Andalucía",
          "Ansermanuevo",
          "Argelia",
          "Bolívar",
          "Buenaventura",
          "Bugalagrande",
          "Caicedonia",
          "Calima",
          "Candelaria",
          "Cartago",
          "Dagua",
          "El Águila",
          "El Cairo",
          "El Cerrito",
          "El Dovio",
          "Florida",
          "Ginebra",
          "Guacarí",
          "Jamundí",
          "La Cumbre",
          "La Unión",
          "La Victoria",
          "Obando",
          "Palmira",
          "Pradera",
          "Restrepo",
          "Riofrío",
          "Roldanillo",
          "San Pedro",
          "Sevilla",
          "Toro",
          "Tuluá",
          "Ulloa",
          "Versalles",
          "Vijes",
          "Yotoco",
          "Yumbo",
          "Zarzal",
        ],
        VAUPES: ["MITU", "Carurú", "Pacoa", "Taraira"],
        VICHADA: [
          "PUERTO_CARREÑO",
          "Cumaribo",
          "La Primavera",
          "Santa Rosalía",
        ],
        LIMA: ["LIMA_CIUDAD"],
      },
      localities: {
        BARRANQUILLA: [
          "Localidad Metropolitana",
          "Localidad Norte-Centro Histórico",
          "Localidad Riomar",
          "Localidad Suroccidente",
          "Localidad Suroriente",
          "Localidad Sur",
        ],
        BOGOTA: [
          "Antonio Nariño",
          "Barrios Unidos",
          "Bosa",
          "Chapinero",
          "Ciudad Bolívar",
          "Engativá",
          "Fontibón",
          "Kennedy",
          "La Candelaria",
          "Los Mártires",
          "Puente Aranda",
          "Rafael Uribe Uribe",
          "San Cristóbal",
          "Santa Fe",
          "Suba",
          "Sumapaz",
          "Teusaquillo",
          "Tunjuelito",
          "Usaquén",
          "Usme",
        ],
        CARTAGENA_DE_INDIAS: [
          "Albornoz",
          "Alcibia",
          "Alto Bosque",
          "Amberes",
          "Antonio José de Sucre",
          "Armenia",
          "Arroz Barato",
          "Barú",
          "Barrio Chino",
          "Bayunca",
          "Bellavista",
          "Blas de Lezo",
          "Bocachica",
          "Bocagrande",
          "Boston",
          "Buenos Aires",
          "Campestre",
          "Canapote",
          "Castellana",
          "Castillogrande",
          "Chambacú",
          "Chiquinquirá",
          "Chipre",
          "Ciudad Amurallada",
          "Colombia",
          "Conjunto Mirador de Zaragocilla",
          "Daniel Lemaitre",
          "El Bosque",
          "El Centro",
          "El Campestre",
          "El Country",
          "El Espinal",
          "El Laguito",
          "El Libertador",
          "El Milagro",
          "El Pozón",
          "El Refugio",
          "España",
          "Fredonia",
          "Getsemaní",
          "Granada",
          "Hipódromo",
          "Junín",
          "La Boquilla",
          "La Concepción",
          "La Esperanza",
          "La María",
          "La Matuna",
          "La Princesa",
          "Las Delicias",
          "Las Gaviotas",
          "Los Caracoles",
          "Los Corales",
          "Mamonal",
          "Manga",
          "Marbella",
          "Media Luna",
          "Nelson Mandela",
          "Nueva Granada",
          "Nuevos Jardines",
          "Pasacaballos",
          "Pie de la Popa",
          "Punta Canoa",
          "San Fernando",
          "San Francisco",
          "San José de los Campanos",
          "San Pedro",
          "Santa Ana",
          "Santa Clara",
          "Santa Isabel",
          "Santander",
          "Santuario",
          "Santuario 2000",
          "Santuario de Paz",
          "Santuario Norte",
          "Santuario Sur",
          "Santo Domingo",
          "Sector la Plazuela",
          "Sert",
          "Torices",
          "Turbana",
          "Urbanización El Recreo",
          "Urbanización La Providencia",
          "Urbanización Los Alpes",
          "Urbanización Los Ejecutivos",
          "Urbanización San Francisco",
          "Urbanización Santa Mónica",
          "Villas de la Candelaria",
          "Villas de Cartagena",
          "Zaragocilla",
        ],
        LETICIA: ["Centro", "Sur", "Norte"],
        PUERTO_SANTANDER: ["Zona 1", "Zona 2"],
        PUERTO_NARIÑO: ["Zona 1", "Zona 2"],
        MEDELLIN: [
          "Altavista",
          "Aranjuez",
          "Belén",
          "Buenos Aires",
          "Castilla",
          "Doce de Octubre",
          "El Poblado",
          "Guayabal",
          "La América",
          "La Candelaria",
          "Laureles - Estadio",
          "Manrique",
          "Popular",
          "Robledo",
          "San Antonio de Prado",
          "San Cristóbal",
          "San Javier",
          "San Sebastián de Palmitas",
          "Santa Cruz",
          "Santa Elena",
          "Villa Hermosa",
        ],
        MANIZALES: [
          "Comuna Atardeceres",
          "Comuna San José",
          "Comuna Cumanday",
          "Comuna La Estación",
          "Comuna Ciudadela del Norte",
          "Comuna Ecoturístico Cerro de Oro",
          "Comuna Universitaria",
          "Comuna Tesorito",
          "Comuna Palogrande",
          "Comuna La Macarena",
          "Comuna La Fuente",
          "Comuna San Jorge",
          "Corregimiento El Remanso",
          "Corregimiento Panorama",
          "Corregimiento La Cabaña",
          "Corregimiento Colombia",
          "Corregimiento Agroturístico",
          "Corregimiento Río Blanco",
          "Corregimiento La Cristalina",
        ],
        TUNJA: [
          "Comuna 1",
          "Comuna 2",
          "Comuna 3",
          "Comuna 4",
          "Comuna 5",
          "Comuna 6",
          "Comuna 7",
          "Comuna 8",
          "Comuna 9",
          "Barón Gallero",
          "Barón Germania",
          "Chorroblanco",
          "El Porvenir",
          "La Esperanza",
          "La Hoya",
          "La Lajita",
          "Pirgua",
          "Runta",
          "Tras del Alto",
        ],
        FLORENCIA: [
          "Comuna Norte",
          "Comuna Occidental",
          "Comuna Suroriental",
          "Comuna Oriental",
          "Caraño",
          "El Danubio",
          "Orteguaza",
          "San Martín",
          "San Pedro",
          "Santo Domingo",
          "Venecia",
        ],
        YOPAL: [
          "Comuna Ciro Reina",
          "Comuna Calixto Zambrano",
          "Comuna Clelia Riveros de Prieto",
          "Comuna Ciudad Campiña",
          "Comuna Javier Manuel Vargas Granados",
          "Comuna Llano Lindo",
          "Comuna La Esmeralda",
        ],
        POPAYAN: [
          "Comuna 1",
          "Comuna 2",
          "Comuna 3",
          "Comuna 4",
          "Comuna 5",
          "Comuna 6",
          "Comuna 7",
          "Comuna 8",
          "Comuna 9",
        ],
        VALLEDUPAR: [
          "Comuna 1",
          "Comuna 2",
          "Comuna 3",
          "Comuna 4",
          "Comuna 5",
          "Comuna 6",
          "Atánquez",
          "Badillo",
          "Chemesquemena",
          "El Alto de La Vuelta",
          "El Jabo",
          "Guacoche",
          "Guacochito",
          "Guatapurí",
          "La Mina",
          "La Vega Arriba",
          "Las Raíces",
          "Los Corazones",
          "Los Haticos",
          "Los Venados",
          "Mariangola",
          "Patillal",
          "Río Seco",
          "Sabana Crespo",
        ],
        QUIBDO: [
          "Comuna 1: Zona Norte",
          "Comuna 2: Porvenir - Platina",
          "Comuna 3: Anillo Central",
          "Comuna 4: San Vicente - Niño Jesús",
          "Comuna 5: Medrano y Zona Sur",
          "Comuna 6: Jardín",
        ],
        MONTERIA: [
          "Comuna 1",
          "Comuna 2",
          "Comuna 3",
          "Comuna 4",
          "Comuna 5",
          "Comuna 6",
          "Comuna 7",
          "Comuna 8",
          "Comuna 9",
        ],
        CUCUTA: [
          "Comuna 1",
          "Comuna 2",
          "Comuna 3",
          "Comuna 4",
          "Comuna 5",
          "Comuna 6",
          "Comuna 7",
          "Comuna 8",
          "Comuna 9",
          "Comuna 10",
        ],
        ARMENIA: [
          "Comuna 1",
          "Comuna 2",
          "Comuna 3",
          "Comuna 4",
          "Comuna 5",
          "Comuna 6",
          "Comuna 7",
          "Comuna 8",
          "Comuna 9",
          "Comuna 10",
        ],
        PEREIRA: [
          "Comuna Olímpica",
          "Comuna Universidad",
          "Comuna Boston",
          "Comuna Consotá",
          "Comuna Río Otún",
          "Comuna El Oso",
          "Comuna Ferrocarril",
          "Comuna Perla del Otún",
          "Comuna El Rocío",
          "Comuna Del Café",
          "Comuna San Joaquín",
          "Comuna Villavicencio",
          "Comuna Cuba",
        ],
        BUCARAMANGA: [
          "Comuna 1 - Norte",
          "Comuna 2 - Nororiental",
          "Comuna 3 - San Francisco",
          "Comuna 4 - Occidental",
          "Comuna 5 - García Rovira",
          "Comuna 6 - La Concordia",
          "Comuna 7 - Ciudadela Real de Minas",
          "Comuna 8 - Sur Occidente",
          "Comuna 9 - La Pedregosa",
          "Comuna 10 - Provenza",
          "Comuna 11 - Sur",
          "Comuna 12 - Cabecera del Llano",
          "Comuna 13 - Oriental",
          "Comuna 14 - Morrorico",
          "Comuna 15 - Centro",
          "Comuna 16 - Lagos del Cacique",
          "Comuna 17 - Mutis",
        ],
        IBAGUE: [
          "Comuna 1",
          "Comuna 2",
          "Comuna 3",
          "Comuna 4",
          "Comuna 5",
          "Comuna 6",
          "Comuna 7",
          "Comuna 8",
          "Comuna 9",
          "Comuna 10",
          "Comuna 11",
          "Comuna 12",
          "Comuna 13",
        ],
        CALI: [
          "Comuna 1",
          "Comuna 2",
          "Comuna 3",
          "Comuna 4",
          "Comuna 5",
          "Comuna 6",
          "Comuna 7",
          "Comuna 8",
          "Comuna 9",
          "Comuna 10",
          "Comuna 11",
          "Comuna 12",
          "Comuna 13",
          "Comuna 14",
          "Comuna 15",
          "Comuna 16",
          "Comuna 17",
          "Comuna 18",
          "Comuna 19",
          "Comuna 20",
          "Comuna 21",
          "Comuna 22",
        ],
        LIMA_CIUDAD: ["Miraflores", "San Isidro"],
      },
    }),
    []
  );
}
